schema_version: 1

context:
  name: smodels
  version: 3.0.1
  # Python 3.8 enforced by numpy requirement
  python_min: 3.8

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/smodels-${{ version }}.tar.gz
  sha256: 52741657b7020f4fb95f4e6cea6254ef59cd29ddc9c0115a040365aff55d0961
  patches:
    - add-build-system.patch
    - add-python_requires.patch
    - add-missing-smodels-tools-printers-sdist-files.patch
    - fix-smodelsLogging-import.patch
    - add-printers-to-packaging.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - smodels-config=smodels.installation:main
      - runSModelS.py=smodels.tools.runSModelS:main
      - smodelsTools.py=smodels.tools.smodelsTools:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - docutils >=0.3
    - numpy >=1.22.0
    - scipy >=1.0.0
    - sympy >=1.0.0
    - unum >=4.0.0
    - requests >=2.0.0
    - pyslha >=3.1.0
    - pyhf >=0.6.1
    - jsonpatch >=1.25
    - jsonschema >=3.2.0

tests:
  - python:
      imports:
        - smodels
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - smodels-config --help
      - runSModelS.py --help
      - smodelsTools.py --help

about:
  summary: A tool for interpreting simplified-model results from the LHC
  license: GPL-3.0-or-later
  license_file: smodels/COPYING
  homepage: http://smodels.github.io/
  repository: https://github.com/SModelS/smodels/
  documentation: http://smodels.github.io/

extra:
  recipe-maintainers:
    - matthewfeickert
